# Generated by Django 2.2.1 on 2019-06-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190606_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parents',
            old_name='present',
            new_name='attdence',
        ),
        migrations.AlterField(
            model_name='student_attendence',
            name='present',
            field=models.BooleanField(default=False),
        ),
    ]
