# Generated by Django 2.2.1 on 2019-06-06 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190606_2321'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parents',
        ),
    ]
