# Generated by Django 2.2.1 on 2019-06-06 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_parents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='roll_no',
        ),
    ]
