# Generated by Django 2.2.1 on 2019-06-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190607_0201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subject',
        ),
        migrations.AddField(
            model_name='student',
            name='subject_name',
            field=models.ManyToManyField(related_name='_student_subject_name_+', to='app.Subject'),
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
