# Generated by Django 2.2.1 on 2019-06-06 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20190607_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
