# Generated by Django 2.2.1 on 2019-06-11 21:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0023_auto_20190612_0233'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_Attendence',
            new_name='Student_Attendance',
        ),
    ]
