# Generated by Django 2.2.1 on 2019-06-11 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20190612_0240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='subject_teacher',
            new_name='subject_name',
        ),
    ]
