# Generated by Django 2.2.1 on 2019-06-11 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20190612_0256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='subject_name',
            new_name='subject_teacher',
        ),
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='app.Subject'),
        ),
    ]
