# Generated by Django 2.2.1 on 2019-06-12 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20190612_0301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='subject_teacher',
        ),
        migrations.AlterField(
            model_name='student_attendance',
            name='present',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent')], default=1, max_length=20),
        ),
    ]
