# Generated by Django 2.2.1 on 2019-06-12 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20190612_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_attendance',
            name='present',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent')], max_length=20),
        ),
    ]
