# Generated by Django 2.2.1 on 2019-06-12 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20190612_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_attendance',
            name='present',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=20),
        ),
    ]
