# Generated by Django 2.2.1 on 2019-06-12 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20190612_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='subject_teacher',
        ),
    ]
