# Generated by Django 2.2.1 on 2019-06-13 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20190613_1315'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parents',
        ),
    ]
