# Generated by Django 2.2.1 on 2019-06-13 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20190613_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='app.Course'),
        ),
    ]
