# Generated by Django 2.2.1 on 2019-06-14 02:20

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20190614_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name=app.models.Student),
        ),
    ]
