# Generated by Django 2.2.1 on 2019-06-14 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20190614_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Student'),
        ),
    ]
