# Generated by Django 2.2.1 on 2019-06-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20190614_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='course',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='department',
        ),
        migrations.AlterField(
            model_name='parent',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
