# Generated by Django 2.2.1 on 2019-07-22 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_exam_out_off'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
